[OpenCL_Headers]
git-tree-sha1 = "f0020bb9d611fcaa0d707dc77f621d29edce6c7b"

    [[OpenCL_Headers.download]]
    sha256 = "7e67365b465e3db1294964fd49ab7cbc5e11461a5816db034bd4f4cd7b674ce8"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2025.5.7+0/OpenCL_Headers.v2025.5.7.any.tar.gz"
