[OpenCL_Headers]
git-tree-sha1 = "a1b6b94a8993982e0a39edbe317a75b2faa89ddf"

    [[OpenCL_Headers.download]]
    sha256 = "07a0de872be426fbc18f9342995d0047d66cddf34bdaed56bd860baf1cabcc9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2023.12.14+0/OpenCL_Headers.v2023.12.14.any.tar.gz"
