[[OpenCL_Headers]]
arch = "i686"
git-tree-sha1 = "ee1695e8d8c1fab31e3dd1a37241c2c6b8e58383"
libc = "musl"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "28b62fedb1ff9b5dcb95f8ed6dfdea656f40f2151ecb8b70e2844c2f0cd9ef2d"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.i686-linux-musl.tar.gz"
[[OpenCL_Headers]]
arch = "aarch64"
git-tree-sha1 = "16b781019836b3cd12404baf3996ad1c65715d3e"
libc = "musl"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "bd4493a1fc1d57c1b3ff7e7bf1a413aab8f68d336fe5094b61cd44255105871a"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.aarch64-linux-musl.tar.gz"
[[OpenCL_Headers]]
arch = "i686"
git-tree-sha1 = "358eef972a8dc65988202610f333a161b0adac81"
os = "windows"

    [[OpenCL_Headers.download]]
    sha256 = "8deca1e72477993e8b812004ae3e453ca976aa1614b7e14d6ffcbd412d7e15b6"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.i686-w64-mingw32.tar.gz"
[[OpenCL_Headers]]
arch = "x86_64"
git-tree-sha1 = "434a0696a932ae4db5d06d2fda71ba285f61722b"
os = "windows"

    [[OpenCL_Headers.download]]
    sha256 = "09b006e9222e820008b83376ad4391c4000aab240cbfb8dcfdde457c02fcabb8"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.x86_64-w64-mingw32.tar.gz"
[[OpenCL_Headers]]
arch = "armv7l"
git-tree-sha1 = "e9dc567f21ca60b03e1b67d8f76486d98cfd6b79"
libc = "glibc"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "04fde249d99ac24045c44a1ceec902853a407fc2f8b9f6c20933ece530b87c32"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.armv7l-linux-gnueabihf.tar.gz"
[[OpenCL_Headers]]
arch = "armv7l"
git-tree-sha1 = "d457326adafac6a4ee1687e6773d4fccf1269a64"
libc = "musl"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "9753a7a054d07cbf13bce1e278de8960e8cd1d0ad72510ceba4aaa437321db92"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.armv7l-linux-musleabihf.tar.gz"
[[OpenCL_Headers]]
arch = "i686"
git-tree-sha1 = "3eae81c4ae572cad66dbff2c820fa1ace6401713"
libc = "glibc"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "8fd9f31c7133f9ae4c89c0ea7a91fcb92721c7a9d746728613e41ebedebfb257"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.i686-linux-gnu.tar.gz"
[[OpenCL_Headers]]
arch = "x86_64"
git-tree-sha1 = "c837a876f3a6ee583b3cd68977ca6738c5960789"
libc = "glibc"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "184f4a6a7ca4a872860ce593610cb5fc01d8b8b0fdd5792befee4fd43c6946de"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.x86_64-linux-gnu.tar.gz"
[[OpenCL_Headers]]
arch = "powerpc64le"
git-tree-sha1 = "e8d361501d53f8f091e2c85d12a317a748332eec"
libc = "glibc"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "356f2dd52adc60b1a355a3a19b4bbffac98c2eb0444b865d22bef7456863a00b"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.powerpc64le-linux-gnu.tar.gz"
[[OpenCL_Headers]]
arch = "x86_64"
git-tree-sha1 = "903494ec647c078edfa77b6b8e88d475608563d8"
os = "macos"

    [[OpenCL_Headers.download]]
    sha256 = "8dae313f9dacaa8d4a05aef65b1d668edf8d5c728fbb0f63a8274f1f2f32e6e8"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.x86_64-apple-darwin14.tar.gz"
[[OpenCL_Headers]]
arch = "aarch64"
git-tree-sha1 = "dbc081d2f55cc398d23e68ffa808ddc814bf42b8"
libc = "glibc"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "7ea6ea068f8017ac41b08b031d3aa53d4932d686631133e9cb5ad772fd4ce632"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.aarch64-linux-gnu.tar.gz"
[[OpenCL_Headers]]
arch = "x86_64"
git-tree-sha1 = "a257996a3358335d8e99de3c919ea0d870bcbfb9"
os = "freebsd"

    [[OpenCL_Headers.download]]
    sha256 = "6984d6c8c08fd138661cdb420b2e178ca5e73858a6515a806cd26d5d8242508c"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.x86_64-unknown-freebsd11.1.tar.gz"
[[OpenCL_Headers]]
arch = "x86_64"
git-tree-sha1 = "ef467d9e19de51dffce15b2050793aa26e333068"
libc = "musl"
os = "linux"

    [[OpenCL_Headers.download]]
    sha256 = "a9200329e237bdd7d73c0ff933ce1b5e9f23a1bbea648a3479c8bc4532479988"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2020.3.13+1/OpenCL_Headers.v2020.3.13.x86_64-linux-musl.tar.gz"
