[OpenCL_Headers]
git-tree-sha1 = "9ec8f68d16a62b259eab252c0cdbfecdf912c1d1"

    [[OpenCL_Headers.download]]
    sha256 = "a62b85bdb5c13eb37fad7cdf3b444949cbbe809c02adf45a469b5cf1d00de632"
    url = "https://github.com/JuliaBinaryWrappers/OpenCL_Headers_jll.jl/releases/download/OpenCL_Headers-v2024.5.8+0/OpenCL_Headers.v2024.5.8.any.tar.gz"
